---
title: "EDA Final Project"
author: "Shubhangi Gupta, Brook Hemphill , Sydney Williams"
date: "04/30/2024"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r packages}
# loading packages
library(tidyverse)
library(dplyr)
library(lubridate)
library(readxl)
library(ggplot2)
library(forecast)
library(Kendall)
library(tseries)
library(outliers)
library(smooth)
library(readr)
library(zoo)
library(readxl)
library(cowplot)
```

# Data Wrangling | Energy Data

```{r wrangle}
#DISTRIBUTED SOLAR PV (<1 MW) IN CALIFORNIA: CAPACITY & GENERATION

#Importing the dataset
CA_DSP_Energy_Raw <- read_excel("EnergyData/CaliforniaDistributedSolarCapGen2015-21.xlsx", col_names=TRUE)
glimpse(CA_DSP_Energy_Raw)

#Price data is quarterly so using electricity data for March, June, September & December
CA_DSP_Energy <- CA_DSP_Energy_Raw[CA_DSP_Energy_Raw$Month %in% c(3, 6, 9, 12),]
  
#Wrangling CA_DSP_Energy Dataset
CA_DSP_Energy <- CA_DSP_Energy %>%
  mutate(Date = paste(Year, Month, sep="-"))%>%
  select("Date", c(,5:12))

#Converting Date column to date object
CA_DSP_Energy$Date <- ym(CA_DSP_Energy$Date)
glimpse(CA_DSP_Energy)

#Rounding the decimal points
CA_DSP_Energy[,c(2:9)]<-round(CA_DSP_Energy[,c(2:9)])

#QUARTERLY ELECTRICTY PRICES FOR SOLAR PV >=10 KW IN CA

#Importing the data
CA_DSP_Prices_Raw <- read_excel("EnergyData/NEMPVPriceData2015-22.xlsx")
glimpse(CA_DSP_Prices_Raw)

#Removing 2015 and 2023 because of incomplete data in these two years
CA_DSP_Prices <- CA_DSP_Prices_Raw[3:30,]
glimpse(CA_DSP_Prices)

#Cleaning the dates
Price_Month <- rep(c(3,6,9,12),7)
CA_DSP_Prices <- cbind(CA_DSP_Prices, Price_Month)
CA_DSP_Prices$Category <- substr(CA_DSP_Prices$Category, start=1, stop=4)
CA_DSP_Prices$Date <- paste0(CA_DSP_Prices$Category,"-",CA_DSP_Prices$Price_Month)
CA_DSP_Prices$Date <- ym(CA_DSP_Prices$Date)

#Removing column with prices for capacity <10kW because not relevant to our analysis
CA_DSP_Prices <- CA_DSP_Prices %>%
  select(c(5,3))
colnames(CA_DSP_Prices) <- c("Date", "Prices")

#COMBINING ELECTRICITY & PRICE DATA INTO ONE DATAFRAME
CA_DSP_Energy_Price <- cbind(CA_DSP_Energy, CA_DSP_Prices$Prices)
colnames(CA_DSP_Energy_Price)[colnames(CA_DSP_Energy_Price)=="CA_DSP_Prices$Prices"]<-"Prices"

# Change column names
colnames(CA_DSP_Energy_Price) <- c("Date", "Cap_Resid", "Cap_Commercial", "Cap_Indus", "Cap_Total", "Gen_Resid", "Gen_Commercial", "Gen_Indus", "Gen_Total", "Prices")

# Plotting California energy prices vs capacity & generation 

CA_Energy_Gen_Plot <- ggplot(CA_DSP_Energy_Price)+
  geom_line(aes(x=CA_DSP_Energy$Date, y=CA_DSP_Energy$`Gen-Total`), color = "green")

CA_Energy_Cap_Plot <- ggplot(CA_DSP_Energy_Price)+
  geom_line(aes(x=CA_DSP_Energy$Date, y=CA_DSP_Energy$`Cap-Total`), color = "orange")

CA_Energy_Price_Plot  <- ggplot(CA_DSP_Energy_Price)+
  geom_line(aes(x=CA_DSP_Prices$Date, y=CA_DSP_Prices$Prices), color = "blue")

plot_grid( CA_Energy_Cap_Plot, CA_Energy_Gen_Plot, CA_Energy_Price_Plot, nrow=1)
```

# Data Analysis | General Linear Model (GLM)

```{r}
#GLM between Price vs Capacity and Generation

DSP_price_capgen_glm <- lm(Prices ~ Cap_Total + Gen_Total, data = CA_DSP_Energy_Price)
print(summary(DSP_price_capgen_glm))

#GLM Between Price vs Residential Capacity and Generation

DSP_price_residcapgen_glm <- lm(Prices ~ Cap_Resid + Gen_Resid, data = CA_DSP_Energy_Price)
print(summary(DSP_price_residcapgen_glm))

#GLM Between Price vs Commercial Capacity and Generation

DSP_price_commercialcapgen_glm <- lm(Prices ~ Cap_Commercial + Gen_Commercial, data = CA_DSP_Energy_Price)
print(summary(DSP_price_commercialcapgen_glm))

#GLM Between Price vs Industrial Capacity and Generation

DSP_price_industrialcapgen_glm <- lm(Prices ~ Cap_Indus + Gen_Indus, data = CA_DSP_Energy_Price)
print(summary(DSP_price_industrialcapgen_glm))

```

## Plotting generation vs prices


```{r}
# Plotting Solar Capacity vs. Electricity Prices
plot(CA_DSP_Energy_Price$Cap_Total, CA_DSP_Energy_Price$Prices, 
     xlab = "Solar PV Capacity", ylab = "Electricity Prices",
     main = "Solar PV Capacity vs Electricity Prices 2015-2021")

# Fitting linear regression model
DSP_price_cap_glm <- lm(Prices ~ Cap_Total, data = CA_DSP_Energy_Price)

# Adding a regression line
abline(DSP_price_cap_glm, col = "red")

```

## [ADD]

```{r}
# Plotting Solar PV Generation vs. Electricity Prices
plot(CA_DSP_Energy_Price$Gen_Total, CA_DSP_Energy_Price$Prices, 
     xlab = "Solar PV Generation", ylab = "Electricity Prices",
     main = "Solar PV Generation vs Electricity Prices 2015-2021")

# Fitting linear regression model
DSP_price_gen_glm <- lm(Prices ~ Gen_Total, data = CA_DSP_Energy_Price)

# Adding a regression line
abline(DSP_price_gen_glm, col = "red")
```

# Conducting a time series analysis on Energy vs Price

```{r}
#Converting the data into a time series
TotalPVCapacity <- CA_DSP_Energy$`Cap-Total`
TotalPVCapacity_ts <- ts(TotalPVCapacity, start = c(2015,1), frequency =4)
TotalPVCapacity_ts

TotalPVGeneration <- CA_DSP_Energy$`Gen-Total`
TotalPVGeneration_ts <- ts(TotalPVGeneration, start = c(2015,1), frequency =4)
TotalPVGeneration_ts

#Decomposing the data
TotalPVCapacity_ts_decomposed <- stl(TotalPVCapacity_ts, s.window="periodic")
plot(TotalPVCapacity_ts_decomposed)

#Checking for trends
print(trend::smk.test(TotalPVCapacity_ts))
```
```

## [ADD]

```{r}
```

## [ADD]

```{r}

```

## [ADD]

```{r}

```

